In [1]:
import pandas as pd
import itertools
from scipy.stats import spearmanr
from scipy.stats import pearsonr
import matplotlib.pyplot as plt
import seaborn as sns

# DATA

In [2]:
cols = ['sample', 'SITE_ID', 'offset_rda', 'marker', 'trait', 
       'POP_SITE', 'POP_ID', 'SET', 'mean', 'sd', 'n', 'group', 'train_group']

In [3]:
df1 = pd.read_csv("01B_garden_compare_rda.tsv", sep="\t", header=0)
df1["train_group"] = "combined"
df1 = df1[cols].reset_index(drop=True)
df1["climate"] = "var3"
df1.head()

,sample,SITE_ID,offset_rda,marker,trait,POP_SITE,POP_ID,SET,mean,sd,n,group,train_group,climate
0,2209_PR,PR,0.082650,1000var5,Height,2209_PR,2209,TEST,980.525258,302.158899,4.0,West,combined,var3
1,325_PR,PR,0.349505,1000var5,Height,325_PR,325,TEST,1239.891145,121.743290,8.0,Central,combined,var3
2,4351_PR,PR,0.363508,1000var5,Height,4351_PR,4351,TEST,1423.598605,68.068593,4.0,Central,combined,var3
3,4420_PR,PR,0.170629,1000var5,Height,4420_PR,4420,TEST,678.153897,154.272486,7.0,West,combined,var3
4,6805_PR,PR,0.257768,1000var5,Height,6805_PR,6805,TEST,1353.974749,229.855027,7.0,East,combined,var3

In [4]:
df2 = pd.read_csv("18_garden_clusters.tsv", sep="\t", header=0)
df2 = df2[cols].reset_index(drop=True)
df2["climate"] = "var3"
df2.head()

,sample,SITE_ID,offset_rda,marker,trait,POP_SITE,POP_ID,SET,mean,sd,n,group,train_group,climate
0,2209_PR,PR,0.433438,1000var5,Height,2209_PR,2209,TEST,980.525258,302.158899,4.0,West,Central,var3
1,325_PR,PR,0.568094,1000var5,Height,325_PR,325,TEST,1239.891145,121.743290,8.0,Central,Central,var3
2,4351_PR,PR,0.580660,1000var5,Height,4351_PR,4351,TEST,1423.598605,68.068593,4.0,Central,Central,var3
3,4420_PR,PR,0.277811,1000var5,Height,4420_PR,4420,TEST,678.153897,154.272486,7.0,West,Central,var3
4,6805_PR,PR,0.407089,1000var5,Height,6805_PR,6805,TEST,1353.974749,229.855027,7.0,East,Central,var3

In [5]:
df3 = pd.read_csv("../951_garden_plot/01B_garden_compare_rda.tsv", sep="\t", header=0)
df3["train_group"] = "combined"
df3 = df3[df3["marker"] == "1000"].reset_index(drop=True)
df3 = df3[cols].reset_index(drop=True)
df3["climate"] = "PC3"
df3.head()

,sample,SITE_ID,offset_rda,marker,trait,POP_SITE,POP_ID,SET,mean,sd,n,group,train_group,climate
0,2209_PR,PR,0.075343,1000,Height,2209_PR,2209,TEST,980.525258,302.158899,4.0,West,combined,PC3
1,325_PR,PR,0.309719,1000,Height,325_PR,325,TEST,1239.891145,121.743290,8.0,Central,combined,PC3
2,4351_PR,PR,0.168758,1000,Height,4351_PR,4351,TEST,1423.598605,68.068593,4.0,Central,combined,PC3
3,4420_PR,PR,0.220976,1000,Height,4420_PR,4420,TEST,678.153897,154.272486,7.0,West,combined,PC3
4,6805_PR,PR,0.242502,1000,Height,6805_PR,6805,TEST,1353.974749,229.855027,7.0,East,combined,PC3

In [6]:
df4 = pd.read_csv("../996_garden_plot_clusters/18_garden_clusters.tsv", sep="\t", header=0)
df4 = df4[cols].reset_index(drop=True)
df4["climate"] = "PC3"
df4.head()

,sample,SITE_ID,offset_rda,marker,trait,POP_SITE,POP_ID,SET,mean,sd,n,group,train_group,climate
0,2209_PR,PR,0.340529,1000,Height,2209_PR,2209,TEST,980.525258,302.158899,4.0,West,Central,PC3
1,325_PR,PR,0.378512,1000,Height,325_PR,325,TEST,1239.891145,121.743290,8.0,Central,Central,PC3
2,4351_PR,PR,0.278826,1000,Height,4351_PR,4351,TEST,1423.598605,68.068593,4.0,Central,Central,PC3
3,4420_PR,PR,0.447724,1000,Height,4420_PR,4420,TEST,678.153897,154.272486,7.0,West,Central,PC3
4,6805_PR,PR,0.339265,1000,Height,6805_PR,6805,TEST,1353.974749,229.855027,7.0,East,Central,PC3

In [7]:
df = pd.concat([df1, df2, df3, df4], ignore_index=True)
df = df[df["SET"] == "TEST"].reset_index(drop=True)
df["train_clim"] = df.apply(lambda x: x["train_group"] + "_" + x["climate"], axis=1)
print(df.shape)
df.head()

(11274, 15)

,sample,SITE_ID,offset_rda,marker,trait,POP_SITE,POP_ID,SET,mean,sd,n,group,train_group,climate,train_clim
0,2209_PR,PR,0.082650,1000var5,Height,2209_PR,2209,TEST,980.525258,302.158899,4.0,West,combined,var3,combined_var3
1,325_PR,PR,0.349505,1000var5,Height,325_PR,325,TEST,1239.891145,121.743290,8.0,Central,combined,var3,combined_var3
2,4351_PR,PR,0.363508,1000var5,Height,4351_PR,4351,TEST,1423.598605,68.068593,4.0,Central,combined,var3,combined_var3
3,4420_PR,PR,0.170629,1000var5,Height,4420_PR,4420,TEST,678.153897,154.272486,7.0,West,combined,var3,combined_var3
4,6805_PR,PR,0.257768,1000var5,Height,6805_PR,6805,TEST,1353.974749,229.855027,7.0,East,combined,var3,combined_var3

# Get paiwise correlations

In [8]:
df_sub = df[(df["SITE_ID"] == "ML") & (df["trait"] == "Height")].reset_index(drop=True)
df_sub.head()

,sample,SITE_ID,offset_rda,marker,trait,POP_SITE,POP_ID,SET,mean,sd,n,group,train_group,climate,train_clim
0,1329_ML,ML,0.105288,1000var5,Height,1329_ML,1329,TEST,1435.746514,165.025251,3.0,East,combined,var3,combined_var3
1,1528_ML,ML,0.094086,1000var5,Height,1528_ML,1528,TEST,1424.030354,75.498344,3.0,East,combined,var3,combined_var3
2,1530_ML,ML,0.234189,1000var5,Height,1530_ML,1530,TEST,976.829721,155.349069,3.0,East,combined,var3,combined_var3
3,1531_ML,ML,0.094940,1000var5,Height,1531_ML,1531,TEST,1186.591020,130.000000,3.0,East,combined,var3,combined_var3
4,1534_ML,ML,0.044385,1000var5,Height,1534_ML,1534,TEST,1367.178745,110.151411,3.0,East,combined,var3,combined_var3

In [9]:
factors = df["train_clim"].unique()
pairs = list(itertools.combinations(factors, 2))
fpairs = [ele for ele in pairs if ("var3" in ele[0]) & ("PC3" in ele[1])]
fpairs

[('combined_var3', 'combined_PC3'),
 ('combined_var3', 'Central_PC3'),
 ('combined_var3', 'West_PC3'),
 ('combined_var3', 'East_PC3'),
 ('Central_var3', 'combined_PC3'),
 ('Central_var3', 'Central_PC3'),
 ('Central_var3', 'West_PC3'),
 ('Central_var3', 'East_PC3'),
 ('West_var3', 'combined_PC3'),
 ('West_var3', 'Central_PC3'),
 ('West_var3', 'West_PC3'),
 ('West_var3', 'East_PC3'),
 ('East_var3', 'combined_PC3'),
 ('East_var3', 'Central_PC3'),
 ('East_var3', 'West_PC3'),
 ('East_var3', 'East_PC3')]

In [10]:
# Get all unique factors and their pairwise combinations

def get_pearsons_corr(dataset):
    factors = dataset["train_clim"].unique()
    pairs = list(itertools.combinations(factors, 2))
    fpairs = [ele for ele in pairs if ("var3" in ele[0]) & ("PC3" in ele[1])]
    
    results = []
    
    for f1, f2 in fpairs:
        v1 = dataset.loc[dataset["train_clim"] == f1, "offset_rda"].values
        v2 = dataset.loc[dataset["train_clim"] == f2, "offset_rda"].values
    
        # Only compare if both have the same number of observations
        n = min(len(v1), len(v2))
        rho, pval = pearsonr(v1[:n], v2[:n])
        rho, pval = pearsonr(v1, v2)
        results.append({"train_clim1": f1, "train_clim2": f2, "r": rho, "p": pval, "n" : n})
    
    pairwise_corr = pd.DataFrame(results)
    return(pairwise_corr)

In [11]:
get_pearsons_corr(df_sub)

     train_clim1   train_clim2         r             p   n
0  combined_var3  combined_PC3  0.903044  1.605127e-15  40
1  combined_var3      East_PC3  0.879067  8.615802e-14  40
2  combined_var3   Central_PC3  0.711923  2.591896e-07  40
3      East_var3  combined_PC3  0.704531  3.900316e-07  40
4      East_var3      East_PC3  0.778583  3.322819e-09  40
5      East_var3   Central_PC3  0.795191  8.837841e-10  40
6   Central_var3  combined_PC3  0.769568  6.509210e-09  40
7   Central_var3      East_PC3  0.809000  2.670857e-10  40
8   Central_var3   Central_PC3  0.857166  1.668161e-12  40

# Loop

In [12]:
R = []
for site in ["PR","ML","CH","AC"]:
    for trait in df['trait'].drop_duplicates().values:
        df_sub = df[(df["SITE_ID"] == site) & (df["trait"] == trait)].reset_index(drop=True)

        df_corrs = get_pearsons_corr(df_sub)
        df_corrs['SITE_ID'] = site
        df_corrs['trait'] = trait
        R.append(df_corrs)
dR = pd.concat(R, ignore_index=True)
dR.head()

     train_clim1   train_clim2         r             p     n SITE_ID   trait
0  combined_var3  combined_PC3  0.836341  1.029745e-07  26.0      PR  Height
1  combined_var3   Central_PC3  0.609360  9.520711e-04  26.0      PR  Height
2  combined_var3      West_PC3  0.777059  3.028119e-06  26.0      PR  Height
3   Central_var3  combined_PC3  0.765408  5.226116e-06  26.0      PR  Height
4   Central_var3   Central_PC3  0.561906  2.814067e-03  26.0      PR  Height

### Saving

In [13]:
dR.to_csv("28_compare_offsets_between_climates_rda.tsv", sep="\t", header=True, index=False)