In [2]:
import pandas as pd
import numpy as np

# DATA

In [14]:
# Black spruce SNPs
df = pd.read_csv("../DATA_intermediate/23_filter_EPN.csv", sep=",", header=0)
print(df.shape)
df.head()

(1467, 29978)

,Unnamed: 0,55749196-29-G/A,55750931-10-C/T,23141276-42-T/A,55764801-6-G/A,100283660-33-C/A,55760984-24-A/G,55749171-62-C/A,55774608-18-A/G,23143410-28-G/A,...,55842229-60-A/G,23149114-12-G/C,55855639-63-T/C,13501202-27-G/A,55836668-31-A/C,23157730-22-T/G,55846148-65-T/C,55836449-6-T/C,55863991-48-C/T,55816615-37-A/G
0,E353-B1_3_6_333_001,0.0,0.0,0.0,0.0,NaN,0.0,1.0,0.0,0.0,...,2.0,1.0,1.0,0.0,2.0,0.0,0.0,NaN,0.0,2.0
1,E353-B1_3_6_6914_073,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,...,2.0,0.0,NaN,1.0,2.0,0.0,0.0,2.0,1.0,2.0
2,E353-B1_3_16_6917_081,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,...,NaN,0.0,0.0,2.0,NaN,1.0,0.0,2.0,NaN,2.0
3,E353-B3_3_7_6802_478,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,2.0,1.0,0.0,1.0,2.0,1.0,NaN,NaN,0.0,2.0
4,E353-B3_3_14_6986_371,0.0,0.0,1.0,0.0,NaN,1.0,2.0,1.0,0.0,...,2.0,1.0,NaN,NaN,0.0,0.0,0.0,2.0,0.0,0.0

# Metadata

Selecting samples from the TRAIN dataset

In [5]:
#dall = pd.read_csv("../44_train_and_test/00_combine_samples.tsv", sep="\t", header=0)
#gall = dall.groupby(["SET","Trait_name","SITE_ID"])["value"].count().reset_index()
#gall.to_excel('01_frequencies_stats.xlsx')
# number stats
#gall.set_index(["SET","Trait_name","SITE_ID"]).unstack().reset_index().to_excel('01_frequencies_stats.xlsx')

In [7]:
dmeta = pd.read_csv("../44_train_and_test/00_combine_samples.tsv", sep="\t", header=0)

# Subset only TRAIN
dmeta = dmeta[dmeta['SET'] == 'TRAIN'].reset_index(drop=True)
print(dmeta.shape)
dmeta.head()

# Train samples

(18282, 9)

,genotype,POP_ID,SITE_ID,call_rate,good_genotype,value,Trait_name,SET,POP_SITE
0,E60-A_4_1_62_260,332,AC,0.870518,True,559.411198,Average_Ring_Density,TRAIN,332_AC
1,E60-A_4_2_62_261,332,AC,0.852943,True,729.561198,Average_Ring_Density,TRAIN,332_AC
2,E60-A_4_7_62_264,332,AC,0.927686,True,565.111198,Average_Ring_Density,TRAIN,332_AC
3,E60-A_5_4_62_562,332,AC,0.898479,True,623.921198,Average_Ring_Density,TRAIN,332_AC
4,E60-A_5_5_62_563,332,AC,0.886400,True,NaN,Average_Ring_Density,TRAIN,332_AC

In [27]:
dmeta['genotype'].drop_duplicates().values

array(['E60-A_4_1_62_260', 'E60-A_4_2_62_261', 'E60-A_4_7_62_264', ...,
       'E353-B1_6_10_6917_718', 'E353-B1_6_6_6979_518', '621-G348-2-3-8'],
      dtype=object)

In [ ]:
stats = dmeta.groupby(["POP_SITE","Trait_name"])[["genotype"]].count().reset_index()
stats[stats["genotype"] <= 4]

# SNPs

In [42]:
# Black spruce SNPs
df = pd.read_csv("../DATA_intermediate/23_filter_EPN.csv", sep=",", header=0, index_col=0)
print(df.shape)
df.head()

(1467, 29977)

,55749196-29-G/A,55750931-10-C/T,23141276-42-T/A,55764801-6-G/A,100283660-33-C/A,55760984-24-A/G,55749171-62-C/A,55774608-18-A/G,23143410-28-G/A,23145710-35-C/T,...,55842229-60-A/G,23149114-12-G/C,55855639-63-T/C,13501202-27-G/A,55836668-31-A/C,23157730-22-T/G,55846148-65-T/C,55836449-6-T/C,55863991-48-C/T,55816615-37-A/G
E353-B1_3_6_333_001,0.0,0.0,0.0,0.0,NaN,0.0,1.0,0.0,0.0,1.0,...,2.0,1.0,1.0,0.0,2.0,0.0,0.0,NaN,0.0,2.0
E353-B1_3_6_6914_073,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,2.0,...,2.0,0.0,NaN,1.0,2.0,0.0,0.0,2.0,1.0,2.0
E353-B1_3_16_6917_081,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,NaN,...,NaN,0.0,0.0,2.0,NaN,1.0,0.0,2.0,NaN,2.0
E353-B3_3_7_6802_478,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,...,2.0,1.0,0.0,1.0,2.0,1.0,NaN,NaN,0.0,2.0
E353-B3_3_14_6986_371,0.0,0.0,1.0,0.0,NaN,1.0,2.0,1.0,0.0,2.0,...,2.0,1.0,NaN,NaN,0.0,0.0,0.0,2.0,0.0,0.0

### Sample subset

In [43]:
df_train = df.loc[dmeta['genotype'].drop_duplicates().values]
print(df_train.shape)
df = []
df_train.columns = ["X" + ele.replace('-','.').replace('/','.') for ele in df_train.columns]
df_train.head()

(1310, 29977)

,X55749196.29.G.A,X55750931.10.C.T,X23141276.42.T.A,X55764801.6.G.A,X100283660.33.C.A,X55760984.24.A.G,X55749171.62.C.A,X55774608.18.A.G,X23143410.28.G.A,X23145710.35.C.T,...,X55842229.60.A.G,X23149114.12.G.C,X55855639.63.T.C,X13501202.27.G.A,X55836668.31.A.C,X23157730.22.T.G,X55846148.65.T.C,X55836449.6.T.C,X55863991.48.C.T,X55816615.37.A.G
E60-A_4_1_62_260,NaN,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,2.0,...,2.0,2.0,0.0,0.0,2.0,0.0,0.0,2.0,1.0,1.0
E60-A_4_2_62_261,0.0,0.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,2.0,...,0.0,1.0,0.0,0.0,2.0,0.0,0.0,2.0,2.0,2.0
E60-A_4_7_62_264,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,...,2.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0
E60-A_5_4_62_562,2.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,2.0,...,2.0,0.0,0.0,0.0,2.0,0.0,0.0,2.0,0.0,2.0
E60-A_5_5_62_563,NaN,0.0,0.0,0.0,NaN,0.0,1.0,0.0,0.0,2.0,...,2.0,0.0,0.0,0.0,2.0,0.0,2.0,NaN,2.0,2.0

# Loop for each trait

In [10]:
traits = dmeta['Trait_name'].drop_duplicates().values.tolist()
traits

['Average_Ring_Density',
 'Biomass_Increment',
 'Biomass_Increment_1980',
 'Biomass_Increment_1985',
 'Biomass_Increment_1990',
 'Biomass_Increment_1995',
 'Biomass_Increment_2000',
 'Biomass_Increment_2005',
 'Biomass_Increment_2010',
 'Biomass_Increment_2015',
 'DBH',
 'Height',
 'Rc',
 'Rl',
 'Rr',
 'Rs']

### One sample example

In [64]:
trait = "Height"
dmeta_sub = dmeta[dmeta['Trait_name'] == trait].reset_index(drop=True)
dmeta_sub = dmeta_sub.set_index("genotype")
    
# Subset genotypes present in metadata (TRAIN)
# List of 1000 SNPs
df_cols = pd.read_csv("../945_GEA_lfmm/05_outlier_genotypes_1000_" + trait + ".tsv", sep="\t", header=0)
df_cols = df_cols.columns.values

# Train samples for the trait
df_sub = df_train.loc[dmeta_sub.index.values]
print(df_sub.shape)
# 1000 genotypes
df_sub = df_sub[df_cols]
print(df_sub.shape)

# Check if the order of index matches
sum(df_sub.index.values == dmeta_sub.index.values)/len(df_sub.index.values)


# Subset genotypes
upper_limit = 2
iteration = 0
random_state = 250828 + upper_limit + iteration


df_grouped = (
    df_sub
    .groupby(dmeta_sub["POP_SITE"])
    .apply(lambda x: x.sample(min(len(x), upper_limit), random_state=random_state))
)

        
# Calculating frequencies
df_all = df_grouped.groupby('POP_SITE').count()*2
            
df_alleles = df_grouped.groupby('POP_SITE').sum()
            
df_af = df_alleles.div(df_all)

(1257, 29977)
(1257, 1000)

In [68]:
df_grouped.head()

                                X55806809.26.A.C  X13496459.13.G.A  \
POP_SITE
1329_CH  E353-B3_5_13_1329_617               0.0               0.0
         E353-B3_4_6_1329_158                0.0               0.0
1329_ML  E353-B1_3_6_1329_157                0.0               0.0
         E353-B1_4_13_1329_305               0.0               0.0
1528_ML  E353-B1_4_6_1528_325                1.0               0.0

                                X55836705.66.T.C  X55863206.22.A.G  \
POP_SITE
1329_CH  E353-B3_5_13_1329_617               0.0               2.0
         E353-B3_4_6_1329_158                1.0               2.0
1329_ML  E353-B1_3_6_1329_157                NaN               0.0
         E353-B1_4_13_1329_305               1.0               0.0
1528_ML  E353-B1_4_6_1528_325                0.0               0.0

                                X13484540.35.G.A  X13495468.51.A.C  \
POP_SITE
1329_CH  E353-B3_5_13_1329_617               1.0               2.0
         E353-B3_4_6_1329_158                1.0               2.0
1329_ML  E353-B1_3_6_1329_157                0.0               0.0
         E353-B1_4_13_1329_305               0.0               2.0
1528_ML  E353-B1_4_6_1528_325                0.0               0.0

                                X55783666.34.C.A  X23150162.16.A.G  \
POP_SITE
1329_CH  E353-B3_5_13_1329_617               0.0               1.0
         E353-B3_4_6_1329_158                0.0               2.0
1329_ML  E353-B1_3_6_1329_157                NaN               2.0
         E353-B1_4_13_1329_305               0.0               2.0
1528_ML  E353-B1_4_6_1528_325                0.0               2.0

                                X23142278.7.T.C  X13502443.35.A.G  ...  \
POP_SITE                                                           ...
1329_CH  E353-B3_5_13_1329_617              0.0               1.0  ...
         E353-B3_4_6_1329_158               0.0               0.0  ...
1329_ML  E353-B1_3_6_1329_157               0.0               NaN  ...
         E353-B1_4_13_1329_305              0.0               1.0  ...
1528_ML  E353-B1_4_6_1528_325               0.0               0.0  ...

                                X13527105.20.A.C  X55816727.67.A.G  \
POP_SITE
1329_CH  E353-B3_5_13_1329_617               1.0               1.0
         E353-B3_4_6_1329_158                NaN               0.0
1329_ML  E353-B1_3_6_1329_157                0.0               0.0
         E353-B1_4_13_1329_305               0.0               2.0
1528_ML  E353-B1_4_6_1528_325                NaN               1.0

                                X55749440.6.C.T  X55762973.22.G.T  \
POP_SITE
1329_CH  E353-B3_5_13_1329_617              0.0               0.0
         E353-B3_4_6_1329_158               0.0               0.0
1329_ML  E353-B1_3_6_1329_157               1.0               0.0
         E353-B1_4_13_1329_305              0.0               0.0
1528_ML  E353-B1_4_6_1528_325               2.0               0.0

                                X55794320.43.C.A  X13511663.37.G.T  \
POP_SITE
1329_CH  E353-B3_5_13_1329_617               0.0               1.0
         E353-B3_4_6_1329_158                1.0               0.0
1329_ML  E353-B1_3_6_1329_157                0.0               1.0
         E353-B1_4_13_1329_305               0.0               0.0
1528_ML  E353-B1_4_6_1528_325                0.0               0.0

                                X55793656.18.C.A  X23141740.47.T.G  \
POP_SITE
1329_CH  E353-B3_5_13_1329_617               1.0               0.0
         E353-B3_4_6_1329_158                0.0               0.0
1329_ML  E353-B1_3_6_1329_157                2.0               0.0
         E353-B1_4_13_1329_305               0.0               0.0
1528_ML  E353-B1_4_6_1528_325                0.0               0.0

                                X55800750.45.A.G  X23147300.12.C.T
POP_SITE
1329_CH  E353-B3_5_13_1329_617               0.0               1.0
         E353-B3_4_6_1329_158                0.0               2.0
1329_ML  E353-B1_3_6_1329_157                NaN               2.0
         E353-B1_4_13_1329_305               0.0               2.0
1528_ML  E353-B1_4_6_1528_325                0.0               2.0

[5 rows x 1000 columns]

In [69]:
dmeta_sub.shape
dmeta_sub.head()

,POP_ID,SITE_ID,call_rate,good_genotype,value,Trait_name,SET,POP_SITE
genotype,,,,,,,,
E60-A_4_1_62_260,332,AC,0.870518,True,1410.138105,Height,TRAIN,332_AC
E60-A_4_2_62_261,332,AC,0.852943,True,1280.138105,Height,TRAIN,332_AC
E60-A_4_7_62_264,332,AC,0.927686,True,1420.138105,Height,TRAIN,332_AC
E60-A_5_4_62_562,332,AC,0.898479,True,1300.138105,Height,TRAIN,332_AC
E60-A_5_5_62_563,332,AC,0.886400,True,1110.138105,Height,TRAIN,332_AC

In [70]:
df_sub.index = df_sub.index.rename("genotype")
df_sub.head()
#df_sub.shape

,X55806809.26.A.C,X13496459.13.G.A,X55836705.66.T.C,X55863206.22.A.G,X13484540.35.G.A,X13495468.51.A.C,X55783666.34.C.A,X23150162.16.A.G,X23142278.7.T.C,X13502443.35.A.G,...,X13527105.20.A.C,X55816727.67.A.G,X55749440.6.C.T,X55762973.22.G.T,X55794320.43.C.A,X13511663.37.G.T,X55793656.18.C.A,X23141740.47.T.G,X55800750.45.A.G,X23147300.12.C.T
genotype,,,,,,,,,,,,,,,,,,,,,
E60-A_4_1_62_260,NaN,NaN,0.0,0.0,1.0,1.0,0.0,2.0,0.0,NaN,...,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
E60-A_4_2_62_261,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,2.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,NaN
E60-A_4_7_62_264,1.0,0.0,0.0,1.0,1.0,1.0,0.0,2.0,0.0,0.0,...,NaN,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0
E60-A_5_4_62_562,0.0,0.0,0.0,0.0,0.0,2.0,NaN,2.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,0.0,1.0
E60-A_5_5_62_563,0.0,0.0,NaN,0.0,1.0,1.0,0.0,2.0,0.0,0.0,...,NaN,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [71]:
# Checking snps with no variation
col_sums = df_af.sum()
cols_to_exclude = col_sums[col_sums==0].index.values.tolist()
df_af = df_af.drop(columns = cols_to_exclude)
print(df_af.shape)
print(len(cols_to_exclude))

(115, 1000)
0

In [72]:
# Cheking columns with nan
nan_cols = df_af.columns[df_af.isna().any()].tolist()
len(nan_cols)

420

In [73]:
dmeta.head()

,genotype,POP_ID,SITE_ID,call_rate,good_genotype,value,Trait_name,SET,POP_SITE
0,E60-A_4_1_62_260,332,AC,0.870518,True,559.411198,Average_Ring_Density,TRAIN,332_AC
1,E60-A_4_2_62_261,332,AC,0.852943,True,729.561198,Average_Ring_Density,TRAIN,332_AC
2,E60-A_4_7_62_264,332,AC,0.927686,True,565.111198,Average_Ring_Density,TRAIN,332_AC
3,E60-A_5_4_62_562,332,AC,0.898479,True,623.921198,Average_Ring_Density,TRAIN,332_AC
4,E60-A_5_5_62_563,332,AC,0.886400,True,NaN,Average_Ring_Density,TRAIN,332_AC

### Loop

In [74]:
for trait in traits:

    dmeta_sub = dmeta[dmeta['Trait_name'] == trait].reset_index(drop=True)
    dmeta_sub = dmeta_sub.set_index("genotype")
        
    # Subset genotypes present in metadata (TRAIN)
    # List of 1000 SNPs
    df_cols = pd.read_csv("../945_GEA_lfmm/05_outlier_genotypes_1000_" + trait + ".tsv", sep="\t", header=0)
    df_cols = df_cols.columns.values
    
    # Train samples for the trait
    df_sub = df_train.loc[dmeta_sub.index.values]
    print(df_sub.shape)
    # 1000 genotypes
    df_sub = df_sub[df_cols]
    print(df_sub.shape)
    
    # Check if the order of index matches
    sum(df_sub.index.values == dmeta_sub.index.values)/len(df_sub.index.values)

    for upper_limit in [2, 4, 6, 8, 10, 12, 14, 100]:
        #print(upper_limit)
        for iteration in range(10):
        #for iteration in range(2):
            #print(iteration)
        
            # Subset genotypes
            random_state = 250828 + upper_limit + iteration

            df_grouped = (
                df_sub
                .groupby(dmeta_sub["POP_SITE"])
                .apply(lambda x: x.sample(min(len(x), upper_limit), random_state=random_state))
            )

            # Save randomly selected samples 
            df_samples = df_grouped.reset_index().rename(columns = {'level_1' : 'genotype'})[['POP_SITE','genotype']]
            df_samples.to_csv('./genotypes_trees/01_samples_POP_' + trait + '_' + str(upper_limit) + '_' + str(iteration) + '.tsv', sep='\t', index=True, header=True)
            
            # Calculating frequencies
            df_all = df_grouped.groupby('POP_SITE').count()*2
            
            df_alleles = df_grouped.groupby('POP_SITE').sum()
            
            df_af = df_alleles.div(df_all)
            stats_1 = df_af.shape[1]
        
            # Checking snps with no variation
            col_sums = df_af.sum()
            cols_to_exclude = col_sums[col_sums==0].index.values.tolist()
            df_af = df_af.drop(columns = cols_to_exclude)
            stats_2 = df_af.shape[1]

            # Checking snps with nans
            nan_cols = df_af.columns[df_af.isna().any()].tolist()
            df_af = df_af.drop(columns = nan_cols)
            stats_3 = df_af.shape
            print(trait, upper_limit, iteration, stats_1, stats_2, stats_3)
            
            # Saving
            df_af.to_csv('./genotypes/01_frequencies_POP_' + trait + '_' + str(upper_limit) + '_' + str(iteration) + '.tsv', sep='\t', index=True, header=True)

(1266, 29977)
(1266, 1000)
Average_Ring_Density 2 0 1000 1000 (115, 549)
Average_Ring_Density 2 1 1000 1000 (115, 542)
Average_Ring_Density 2 2 1000 1000 (115, 579)
Average_Ring_Density 2 3 1000 1000 (115, 537)
Average_Ring_Density 2 4 1000 1000 (115, 542)
Average_Ring_Density 2 5 1000 1000 (115, 554)
Average_Ring_Density 2 6 1000 1000 (115, 541)
Average_Ring_Density 2 7 1000 1000 (115, 531)
Average_Ring_Density 2 8 1000 1000 (115, 549)
Average_Ring_Density 2 9 1000 1000 (115, 550)
Average_Ring_Density 4 0 1000 1000 (115, 892)
Average_Ring_Density 4 1 1000 1000 (115, 905)
Average_Ring_Density 4 2 1000 1000 (115, 907)
Average_Ring_Density 4 3 1000 1000 (115, 904)
Average_Ring_Density 4 4 1000 1000 (115, 899)
Average_Ring_Density 4 5 1000 1000 (115, 894)
Average_Ring_Density 4 6 1000 1000 (115, 897)
Average_Ring_Density 4 7 1000 1000 (115, 899)
Average_Ring_Density 4 8 1000 1000 (115, 897)
Average_Ring_Density 4 9 1000 1000 (115, 902)
Average_Ring_Density 6 0 1000 1000 (115, 979)
Average_Ring_Density 6 1 1000 1000 (115, 978)
Average_Ring_Density 6 2 1000 1000 (115, 975)
Average_Ring_Density 6 3 1000 1000 (115, 977)
Average_Ring_Density 6 4 1000 1000 (115, 984)
Average_Ring_Density 6 5 1000 1000 (115, 978)
Average_Ring_Density 6 6 1000 1000 (115, 977)
Average_Ring_Density 6 7 1000 1000 (115, 977)
Average_Ring_Density 6 8 1000 1000 (115, 970)
Average_Ring_Density 6 9 1000 1000 (115, 982)
Average_Ring_Density 8 0 1000 1000 (115, 993)
Average_Ring_Density 8 1 1000 1000 (115, 996)
Average_Ring_Density 8 2 1000 1000 (115, 997)
Average_Ring_Density 8 3 1000 1000 (115, 996)
Average_Ring_Density 8 4 1000 1000 (115, 993)
Average_Ring_Density 8 5 1000 1000 (115, 997)
Average_Ring_Density 8 6 1000 1000 (115, 995)
Average_Ring_Density 8 7 1000 1000 (115, 998)
Average_Ring_Density 8 8 1000 1000 (115, 996)
Average_Ring_Density 8 9 1000 1000 (115, 996)
Average_Ring_Density 10 0 1000 1000 (115, 1000)
Average_Ring_Density 10 1 1000 1000 (115, 1000)
Average_Ring_Density 10 2 1000 1000 (115, 999)
Average_Ring_Density 10 3 1000 1000 (115, 999)
Average_Ring_Density 10 4 1000 1000 (115, 1000)
Average_Ring_Density 10 5 1000 1000 (115, 999)
Average_Ring_Density 10 6 1000 1000 (115, 1000)
Average_Ring_Density 10 7 1000 1000 (115, 999)
Average_Ring_Density 10 8 1000 1000 (115, 1000)
Average_Ring_Density 10 9 1000 1000 (115, 1000)
Average_Ring_Density 12 0 1000 1000 (115, 1000)
Average_Ring_Density 12 1 1000 1000 (115, 1000)
Average_Ring_Density 12 2 1000 1000 (115, 1000)
Average_Ring_Density 12 3 1000 1000 (115, 1000)
Average_Ring_Density 12 4 1000 1000 (115, 1000)
Average_Ring_Density 12 5 1000 1000 (115, 1000)
Average_Ring_Density 12 6 1000 1000 (115, 1000)
Average_Ring_Density 12 7 1000 1000 (115, 1000)
Average_Ring_Density 12 8 1000 1000 (115, 1000)
Average_Ring_Density 12 9 1000 1000 (115, 999)
Average_Ring_Density 14 0 1000 1000 (115, 1000)
Average_Ring_Density 14 1 1000 1000 (115, 1000)
Average_Ring_Density 14 2 1000 1000 (115, 1000)
Average_Ring_Density 14 3 1000 1000 (115, 1000)
Average_Ring_Density 14 4 1000 1000 (115, 1000)
Average_Ring_Density 14 5 1000 1000 (115, 1000)
Average_Ring_Density 14 6 1000 1000 (115, 1000)
Average_Ring_Density 14 7 1000 1000 (115, 999)
Average_Ring_Density 14 8 1000 1000 (115, 1000)
Average_Ring_Density 14 9 1000 1000 (115, 1000)
Average_Ring_Density 100 0 1000 1000 (115, 1000)
Average_Ring_Density 100 1 1000 1000 (115, 1000)
Average_Ring_Density 100 2 1000 1000 (115, 1000)
Average_Ring_Density 100 3 1000 1000 (115, 1000)
Average_Ring_Density 100 4 1000 1000 (115, 1000)
Average_Ring_Density 100 5 1000 1000 (115, 1000)
Average_Ring_Density 100 6 1000 1000 (115, 1000)
Average_Ring_Density 100 7 1000 1000 (115, 1000)
Average_Ring_Density 100 8 1000 1000 (115, 1000)
Average_Ring_Density 100 9 1000 1000 (115, 1000)
(1266, 29977)
(1266, 1000)
Biomass_Increment 2 0 1000 1000 (115, 552)
Biomass_Increment 2 1 1000 1000 (115, 550)
Biomass_Increment 2 2 1000 1000 (115, 570)
Biomass_Increment 2 3 1000 1000 (115, 549)
Biomass_Increment 2 4 1000 1000 (115, 561)
Biomass_Increment 2 5 1000 1000 (115, 565)
Biomass_Increment 2 6 1000 1000 (115, 539)
Biomass_Increment 2 7 1000 1000 (115, 561)
Biomass_Increment 2 8 1000 1000 (115, 549)
Biomass_Increment 2 9 1000 1000 (115, 535)
Biomass_Increment 4 0 1000 1000 (115, 894)
Biomass_Increment 4 1 1000 1000 (115, 883)
Biomass_Increment 4 2 1000 1000 (115, 880)
Biomass_Increment 4 3 1000 1000 (115, 883)
Biomass_Increment 4 4 1000 1000 (115, 874)
Biomass_Increment 4 5 1000 1000 (115, 877)
Biomass_Increment 4 6 1000 1000 (115, 889)
Biomass_Increment 4 7 1000 1000 (115, 875)
Biomass_Increment 4 8 1000 1000 (115, 869)
Biomass_Increment 4 9 1000 1000 (115, 878)
Biomass_Increment 6 0 1000 1000 (115, 973)
Biomass_Increment 6 1 1000 1000 (115, 974)
Biomass_Increment 6 2 1000 1000 (115, 973)
Biomass_Increment 6 3 1000 1000 (115, 970)
Biomass_Increment 6 4 1000 1000 (115, 978)
Biomass_Increment 6 5 1000 1000 (115, 978)
Biomass_Increment 6 6 1000 1000 (115, 973)
Biomass_Increment 6 7 1000 1000 (115, 967)
Biomass_Increment 6 8 1000 1000 (115, 976)
Biomass_Increment 6 9 1000 1000 (115, 974)
Biomass_Increment 8 0 1000 1000 (115, 993)
Biomass_Increment 8 1 1000 1000 (115, 994)
Biomass_Increment 8 2 1000 1000 (115, 992)
Biomass_Increment 8 3 1000 1000 (115, 993)
Biomass_Increment 8 4 1000 1000 (115, 993)
Biomass_Increment 8 5 1000 1000 (115, 992)
Biomass_Increment 8 6 1000 1000 (115, 994)
Biomass_Increment 8 7 1000 1000 (115, 992)
Biomass_Increment 8 8 1000 1000 (115, 995)
Biomass_Increment 8 9 1000 1000 (115, 992)
Biomass_Increment 10 0 1000 1000 (115, 1000)
Biomass_Increment 10 1 1000 1000 (115, 997)
Biomass_Increment 10 2 1000 1000 (115, 999)
Biomass_Increment 10 3 1000 1000 (115, 1000)
Biomass_Increment 10 4 1000 1000 (115, 997)
Biomass_Increment 10 5 1000 1000 (115, 996)
Biomass_Increment 10 6 1000 1000 (115, 1000)
Biomass_Increment 10 7 1000 1000 (115, 996)
Biomass_Increment 10 8 1000 1000 (115, 998)
Biomass_Increment 10 9 1000 1000 (115, 997)
Biomass_Increment 12 0 1000 1000 (115, 1000)
Biomass_Increment 12 1 1000 1000 (115, 1000)
Biomass_Increment 12 2 1000 1000 (115, 999)
Biomass_Increment 12 3 1000 1000 (115, 1000)
Biomass_Increment 12 4 1000 1000 (115, 1000)
Biomass_Increment 12 5 1000 1000 (115, 1000)
Biomass_Increment 12 6 1000 1000 (115, 1000)
Biomass_Increment 12 7 1000 1000 (115, 998)
Biomass_Increment 12 8 1000 1000 (115, 1000)
Biomass_Increment 12 9 1000 1000 (115, 1000)
Biomass_Increment 14 0 1000 1000 (115, 1000)
Biomass_Increment 14 1 1000 1000 (115, 1000)
Biomass_Increment 14 2 1000 1000 (115, 1000)
Biomass_Increment 14 3 1000 1000 (115, 1000)
Biomass_Increment 14 4 1000 1000 (115, 1000)
Biomass_Increment 14 5 1000 1000 (115, 1000)
Biomass_Increment 14 6 1000 1000 (115, 1000)
Biomass_Increment 14 7 1000 1000 (115, 1000)
Biomass_Increment 14 8 1000 1000 (115, 1000)
Biomass_Increment 14 9 1000 1000 (115, 1000)
Biomass_Increment 100 0 1000 1000 (115, 1000)
Biomass_Increment 100 1 1000 1000 (115, 1000)
Biomass_Increment 100 2 1000 1000 (115, 1000)
Biomass_Increment 100 3 1000 1000 (115, 1000)
Biomass_Increment 100 4 1000 1000 (115, 1000)
Biomass_Increment 100 5 1000 1000 (115, 1000)
Biomass_Increment 100 6 1000 1000 (115, 1000)
Biomass_Increment 100 7 1000 1000 (115, 1000)
Biomass_Increment 100 8 1000 1000 (115, 1000)
Biomass_Increment 100 9 1000 1000 (115, 1000)
(683, 29977)
(683, 1000)
Biomass_Increment_1980 2 0 1000 1000 (87, 573)
Biomass_Increment_1980 2 1 1000 1000 (87, 562)
Biomass_Increment_1980 2 2 1000 1000 (87, 594)
Biomass_Increment_1980 2 3 1000 1000 (87, 569)
Biomass_Increment_1980 2 4 1000 1000 (87, 579)
Biomass_Increment_1980 2 5 1000 1000 (87, 578)
Biomass_Increment_1980 2 6 1000 1000 (87, 583)
Biomass_Increment_1980 2 7 1000 1000 (87, 590)
Biomass_Increment_1980 2 8 1000 1000 (87, 585)
Biomass_Increment_1980 2 9 1000 1000 (87, 579)
Biomass_Increment_1980 4 0 1000 1000 (87, 919)
Biomass_Increment_1980 4 1 1000 1000 (87, 899)
Biomass_Increment_1980 4 2 1000 1000 (87, 906)
Biomass_Increment_1980 4 3 1000 1000 (87, 907)
Biomass_Increment_1980 4 4 1000 1000 (87, 891)
Biomass_Increment_1980 4 5 1000 1000 (87, 909)
Biomass_Increment_1980 4 6 1000 1000 (87, 904)
Biomass_Increment_1980 4 7 1000 1000 (87, 889)
Biomass_Increment_1980 4 8 1000 1000 (87, 892)
Biomass_Increment_1980 4 9 1000 1000 (87, 906)
Biomass_Increment_1980 6 0 1000 1000 (87, 975)
Biomass_Increment_1980 6 1 1000 1000 (87, 978)
Biomass_Increment_1980 6 2 1000 1000 (87, 985)
Biomass_Increment_1980 6 3 1000 1000 (87, 989)
Biomass_Increment_1980 6 4 1000 1000 (87, 978)
Biomass_Increment_1980 6 5 1000 1000 (87, 978)
Biomass_Increment_1980 6 6 1000 1000 (87, 980)
Biomass_Increment_1980 6 7 1000 1000 (87, 981)
Biomass_Increment_1980 6 8 1000 1000 (87, 981)
Biomass_Increment_1980 6 9 1000 1000 (87, 978)
Biomass_Increment_1980 8 0 1000 1000 (87, 998)
Biomass_Increment_1980 8 1 1000 1000 (87, 996)
Biomass_Increment_1980 8 2 1000 1000 (87, 997)
Biomass_Increment_1980 8 3 1000 1000 (87, 993)
Biomass_Increment_1980 8 4 1000 1000 (87, 997)
Biomass_Increment_1980 8 5 1000 1000 (87, 998)
Biomass_Increment_1980 8 6 1000 1000 (87, 997)
Biomass_Increment_1980 8 7 1000 1000 (87, 994)
Biomass_Increment_1980 8 8 1000 1000 (87, 998)
Biomass_Increment_1980 8 9 1000 1000 (87, 993)
Biomass_Increment_1980 10 0 1000 1000 (87, 1000)
Biomass_Increment_1980 10 1 1000 1000 (87, 1000)
Biomass_Increment_1980 10 2 1000 1000 (87, 1000)
Biomass_Increment_1980 10 3 1000 1000 (87, 999)
Biomass_Increment_1980 10 4 1000 1000 (87, 999)
Biomass_Increment_1980 10 5 1000 1000 (87, 1000)
Biomass_Increment_1980 10 6 1000 1000 (87, 1000)
Biomass_Increment_1980 10 7 1000 1000 (87, 1000)
Biomass_Increment_1980 10 8 1000 1000 (87, 999)
Biomass_Increment_1980 10 9 1000 1000 (87, 998)
Biomass_Increment_1980 12 0 1000 1000 (87, 1000)
Biomass_Increment_1980 12 1 1000 1000 (87, 1000)
Biomass_Increment_1980 12 2 1000 1000 (87, 1000)
Biomass_Increment_1980 12 3 1000 1000 (87, 1000)
Biomass_Increment_1980 12 4 1000 1000 (87, 1000)
Biomass_Increment_1980 12 5 1000 1000 (87, 1000)
Biomass_Increment_1980 12 6 1000 1000 (87, 1000)
Biomass_Increment_1980 12 7 1000 1000 (87, 1000)
Biomass_Increment_1980 12 8 1000 1000 (87, 1000)
Biomass_Increment_1980 12 9 1000 1000 (87, 1000)
Biomass_Increment_1980 14 0 1000 1000 (87, 1000)
Biomass_Increment_1980 14 1 1000 1000 (87, 1000)
Biomass_Increment_1980 14 2 1000 1000 (87, 1000)
Biomass_Increment_1980 14 3 1000 1000 (87, 1000)
Biomass_Increment_1980 14 4 1000 1000 (87, 1000)
Biomass_Increment_1980 14 5 1000 1000 (87, 1000)
Biomass_Increment_1980 14 6 1000 1000 (87, 1000)
Biomass_Increment_1980 14 7 1000 1000 (87, 1000)
Biomass_Increment_1980 14 8 1000 1000 (87, 1000)
Biomass_Increment_1980 14 9 1000 1000 (87, 1000)
Biomass_Increment_1980 100 0 1000 1000 (87, 1000)
Biomass_Increment_1980 100 1 1000 1000 (87, 1000)
Biomass_Increment_1980 100 2 1000 1000 (87, 1000)
Biomass_Increment_1980 100 3 1000 1000 (87, 1000)
Biomass_Increment_1980 100 4 1000 1000 (87, 1000)
Biomass_Increment_1980 100 5 1000 1000 (87, 1000)
Biomass_Increment_1980 100 6 1000 1000 (87, 1000)
Biomass_Increment_1980 100 7 1000 1000 (87, 1000)
Biomass_Increment_1980 100 8 1000 1000 (87, 1000)
Biomass_Increment_1980 100 9 1000 1000 (87, 1000)
(1114, 29977)
(1114, 1000)
Biomass_Increment_1985 2 0 1000 1000 (110, 549)
Biomass_Increment_1985 2 1 1000 1000 (110, 537)
Biomass_Increment_1985 2 2 1000 1000 (110, 571)
Biomass_Increment_1985 2 3 1000 1000 (110, 541)
Biomass_Increment_1985 2 4 1000 1000 (110, 534)
Biomass_Increment_1985 2 5 1000 1000 (110, 555)
Biomass_Increment_1985 2 6 1000 1000 (110, 539)
Biomass_Increment_1985 2 7 1000 1000 (110, 532)
Biomass_Increment_1985 2 8 1000 1000 (110, 530)
Biomass_Increment_1985 2 9 1000 1000 (110, 543)
Biomass_Increment_1985 4 0 1000 1000 (110, 890)
Biomass_Increment_1985 4 1 1000 1000 (110, 891)
Biomass_Increment_1985 4 2 1000 1000 (110, 901)
Biomass_Increment_1985 4 3 1000 1000 (110, 885)
Biomass_Increment_1985 4 4 1000 1000 (110, 881)
Biomass_Increment_1985 4 5 1000 1000 (110, 896)
Biomass_Increment_1985 4 6 1000 1000 (110, 901)
Biomass_Increment_1985 4 7 1000 1000 (110, 881)
Biomass_Increment_1985 4 8 1000 1000 (110, 896)
Biomass_Increment_1985 4 9 1000 1000 (110, 892)
Biomass_Increment_1985 6 0 1000 1000 (110, 983)
Biomass_Increment_1985 6 1 1000 1000 (110, 975)
Biomass_Increment_1985 6 2 1000 1000 (110, 969)
Biomass_Increment_1985 6 3 1000 1000 (110, 969)
Biomass_Increment_1985 6 4 1000 1000 (110, 978)
Biomass_Increment_1985 6 5 1000 1000 (110, 972)
Biomass_Increment_1985 6 6 1000 1000 (110, 976)
Biomass_Increment_1985 6 7 1000 1000 (110, 976)
Biomass_Increment_1985 6 8 1000 1000 (110, 971)
Biomass_Increment_1985 6 9 1000 1000 (110, 977)
Biomass_Increment_1985 8 0 1000 1000 (110, 986)
Biomass_Increment_1985 8 1 1000 1000 (110, 993)
Biomass_Increment_1985 8 2 1000 1000 (110, 991)
Biomass_Increment_1985 8 3 1000 1000 (110, 993)
Biomass_Increment_1985 8 4 1000 1000 (110, 993)
Biomass_Increment_1985 8 5 1000 1000 (110, 997)
Biomass_Increment_1985 8 6 1000 1000 (110, 992)
Biomass_Increment_1985 8 7 1000 1000 (110, 990)
Biomass_Increment_1985 8 8 1000 1000 (110, 996)
Biomass_Increment_1985 8 9 1000 1000 (110, 994)
Biomass_Increment_1985 10 0 1000 1000 (110, 999)
Biomass_Increment_1985 10 1 1000 1000 (110, 997)
Biomass_Increment_1985 10 2 1000 1000 (110, 999)
Biomass_Increment_1985 10 3 1000 1000 (110, 998)
Biomass_Increment_1985 10 4 1000 1000 (110, 998)
Biomass_Increment_1985 10 5 1000 1000 (110, 999)
Biomass_Increment_1985 10 6 1000 1000 (110, 999)
Biomass_Increment_1985 10 7 1000 1000 (110, 999)
Biomass_Increment_1985 10 8 1000 1000 (110, 1000)
Biomass_Increment_1985 10 9 1000 1000 (110, 1000)
Biomass_Increment_1985 12 0 1000 1000 (110, 1000)
Biomass_Increment_1985 12 1 1000 1000 (110, 1000)
Biomass_Increment_1985 12 2 1000 1000 (110, 999)
Biomass_Increment_1985 12 3 1000 1000 (110, 1000)
Biomass_Increment_1985 12 4 1000 1000 (110, 1000)
Biomass_Increment_1985 12 5 1000 1000 (110, 999)
Biomass_Increment_1985 12 6 1000 1000 (110, 1000)
Biomass_Increment_1985 12 7 1000 1000 (110, 1000)
Biomass_Increment_1985 12 8 1000 1000 (110, 1000)
Biomass_Increment_1985 12 9 1000 1000 (110, 1000)
Biomass_Increment_1985 14 0 1000 1000 (110, 1000)
Biomass_Increment_1985 14 1 1000 1000 (110, 1000)
Biomass_Increment_1985 14 2 1000 1000 (110, 1000)
Biomass_Increment_1985 14 3 1000 1000 (110, 1000)
Biomass_Increment_1985 14 4 1000 1000 (110, 1000)
Biomass_Increment_1985 14 5 1000 1000 (110, 1000)
Biomass_Increment_1985 14 6 1000 1000 (110, 1000)
Biomass_Increment_1985 14 7 1000 1000 (110, 1000)
Biomass_Increment_1985 14 8 1000 1000 (110, 1000)
Biomass_Increment_1985 14 9 1000 1000 (110, 1000)
Biomass_Increment_1985 100 0 1000 1000 (110, 1000)
Biomass_Increment_1985 100 1 1000 1000 (110, 1000)
Biomass_Increment_1985 100 2 1000 1000 (110, 1000)
Biomass_Increment_1985 100 3 1000 1000 (110, 1000)
Biomass_Increment_1985 100 4 1000 1000 (110, 1000)
Biomass_Increment_1985 100 5 1000 1000 (110, 1000)
Biomass_Increment_1985 100 6 1000 1000 (110, 1000)
Biomass_Increment_1985 100 7 1000 1000 (110, 1000)
Biomass_Increment_1985 100 8 1000 1000 (110, 1000)
Biomass_Increment_1985 100 9 1000 1000 (110, 1000)
(1250, 29977)
(1250, 1000)
Biomass_Increment_1990 2 0 1000 1000 (114, 554)
Biomass_Increment_1990 2 1 1000 1000 (114, 542)
Biomass_Increment_1990 2 2 1000 1000 (114, 564)
Biomass_Increment_1990 2 3 1000 1000 (114, 539)
Biomass_Increment_1990 2 4 1000 1000 (114, 545)
Biomass_Increment_1990 2 5 1000 1000 (114, 550)
Biomass_Increment_1990 2 6 1000 1000 (114, 546)
Biomass_Increment_1990 2 7 1000 1000 (114, 549)
Biomass_Increment_1990 2 8 1000 1000 (114, 550)
Biomass_Increment_1990 2 9 1000 1000 (114, 551)
Biomass_Increment_1990 4 0 1000 1000 (114, 889)
Biomass_Increment_1990 4 1 1000 1000 (114, 892)
Biomass_Increment_1990 4 2 1000 1000 (114, 890)
Biomass_Increment_1990 4 3 1000 1000 (114, 882)
Biomass_Increment_1990 4 4 1000 1000 (114, 891)
Biomass_Increment_1990 4 5 1000 1000 (114, 893)
Biomass_Increment_1990 4 6 1000 1000 (114, 890)
Biomass_Increment_1990 4 7 1000 1000 (114, 889)
Biomass_Increment_1990 4 8 1000 1000 (114, 885)
Biomass_Increment_1990 4 9 1000 1000 (114, 879)
Biomass_Increment_1990 6 0 1000 1000 (114, 978)
Biomass_Increment_1990 6 1 1000 1000 (114, 965)
Biomass_Increment_1990 6 2 1000 1000 (114, 969)
Biomass_Increment_1990 6 3 1000 1000 (114, 980)
Biomass_Increment_1990 6 4 1000 1000 (114, 972)
Biomass_Increment_1990 6 5 1000 1000 (114, 967)
Biomass_Increment_1990 6 6 1000 1000 (114, 971)
Biomass_Increment_1990 6 7 1000 1000 (114, 963)
Biomass_Increment_1990 6 8 1000 1000 (114, 974)
Biomass_Increment_1990 6 9 1000 1000 (114, 972)
Biomass_Increment_1990 8 0 1000 1000 (114, 986)
Biomass_Increment_1990 8 1 1000 1000 (114, 997)
Biomass_Increment_1990 8 2 1000 1000 (114, 989)
Biomass_Increment_1990 8 3 1000 1000 (114, 989)
Biomass_Increment_1990 8 4 1000 1000 (114, 992)
Biomass_Increment_1990 8 5 1000 1000 (114, 990)
Biomass_Increment_1990 8 6 1000 1000 (114, 992)
Biomass_Increment_1990 8 7 1000 1000 (114, 989)
Biomass_Increment_1990 8 8 1000 1000 (114, 992)
Biomass_Increment_1990 8 9 1000 1000 (114, 993)
Biomass_Increment_1990 10 0 1000 1000 (114, 996)
Biomass_Increment_1990 10 1 1000 1000 (114, 997)
Biomass_Increment_1990 10 2 1000 1000 (114, 996)
Biomass_Increment_1990 10 3 1000 1000 (114, 996)
Biomass_Increment_1990 10 4 1000 1000 (114, 998)
Biomass_Increment_1990 10 5 1000 1000 (114, 998)
Biomass_Increment_1990 10 6 1000 1000 (114, 998)
Biomass_Increment_1990 10 7 1000 1000 (114, 999)
Biomass_Increment_1990 10 8 1000 1000 (114, 997)
Biomass_Increment_1990 10 9 1000 1000 (114, 998)
Biomass_Increment_1990 12 0 1000 1000 (114, 1000)
Biomass_Increment_1990 12 1 1000 1000 (114, 999)
Biomass_Increment_1990 12 2 1000 1000 (114, 999)
Biomass_Increment_1990 12 3 1000 1000 (114, 1000)
Biomass_Increment_1990 12 4 1000 1000 (114, 1000)
Biomass_Increment_1990 12 5 1000 1000 (114, 1000)
Biomass_Increment_1990 12 6 1000 1000 (114, 1000)
Biomass_Increment_1990 12 7 1000 1000 (114, 1000)
Biomass_Increment_1990 12 8 1000 1000 (114, 999)
Biomass_Increment_1990 12 9 1000 1000 (114, 1000)
Biomass_Increment_1990 14 0 1000 1000 (114, 1000)
Biomass_Increment_1990 14 1 1000 1000 (114, 1000)
Biomass_Increment_1990 14 2 1000 1000 (114, 1000)
Biomass_Increment_1990 14 3 1000 1000 (114, 1000)
Biomass_Increment_1990 14 4 1000 1000 (114, 1000)
Biomass_Increment_1990 14 5 1000 1000 (114, 1000)
Biomass_Increment_1990 14 6 1000 1000 (114, 1000)
Biomass_Increment_1990 14 7 1000 1000 (114, 1000)
Biomass_Increment_1990 14 8 1000 1000 (114, 1000)
Biomass_Increment_1990 14 9 1000 1000 (114, 1000)
Biomass_Increment_1990 100 0 1000 1000 (114, 1000)
Biomass_Increment_1990 100 1 1000 1000 (114, 1000)
Biomass_Increment_1990 100 2 1000 1000 (114, 1000)
Biomass_Increment_1990 100 3 1000 1000 (114, 1000)
Biomass_Increment_1990 100 4 1000 1000 (114, 1000)
Biomass_Increment_1990 100 5 1000 1000 (114, 1000)
Biomass_Increment_1990 100 6 1000 1000 (114, 1000)
Biomass_Increment_1990 100 7 1000 1000 (114, 1000)
Biomass_Increment_1990 100 8 1000 1000 (114, 1000)
Biomass_Increment_1990 100 9 1000 1000 (114, 1000)
(1266, 29977)
(1266, 1000)
Biomass_Increment_1995 2 0 1000 1000 (115, 559)
Biomass_Increment_1995 2 1 1000 1000 (115, 546)
Biomass_Increment_1995 2 2 1000 1000 (115, 577)
Biomass_Increment_1995 2 3 1000 1000 (115, 561)
Biomass_Increment_1995 2 4 1000 1000 (115, 549)
Biomass_Increment_1995 2 5 1000 1000 (115, 547)
Biomass_Increment_1995 2 6 1000 1000 (115, 556)
Biomass_Increment_1995 2 7 1000 1000 (115, 553)
Biomass_Increment_1995 2 8 1000 1000 (115, 544)
Biomass_Increment_1995 2 9 1000 1000 (115, 552)
Biomass_Increment_1995 4 0 1000 1000 (115, 866)
Biomass_Increment_1995 4 1 1000 1000 (115, 856)
Biomass_Increment_1995 4 2 1000 1000 (115, 867)
Biomass_Increment_1995 4 3 1000 1000 (115, 868)
Biomass_Increment_1995 4 4 1000 1000 (115, 879)
Biomass_Increment_1995 4 5 1000 1000 (115, 868)
Biomass_Increment_1995 4 6 1000 1000 (115, 872)
Biomass_Increment_1995 4 7 1000 1000 (115, 872)