In [1]:
import pandas as pd
import numpy as np

# DATA

In [9]:
# Black spruce SNPs without filtering for MAF
df = pd.read_csv("../929_heterozygosity/01_prep_inputs_II.csv", sep=",", header=0, index_col=0)
df_samples = df.index.values
df.head()

,POP,55749196-29-G/A,100283399-40-C/T,100283400-45-A/C,55750931-10-C/T,23141276-42-T/A,100283428-17-C/T,100283429-66-T/A,23147835-9-C/T,100283457-18-C/A,...,13501202-27-G/A,55836668-31-A/C,23157730-22-T/G,55846148-65-T/C,55860316-28-G/C,55836449-6-T/C,55863991-48-C/T,102640963-40-T/A,55816615-37-A/G,102641000-63-A/G
id,,,,,,,,,,,,,,,,,,,,,
E353-B1_3_6_333_001,333,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,NaN,0.0,0.0,2.0,NaN
E353-B1_3_6_6914_073,6914,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,2.0,0.0,0.0,0.0,2.0,1.0,NaN,2.0,NaN
E353-B1_3_16_6917_081,6917,0.0,0.0,2.0,0.0,0.0,NaN,0.0,0.0,0.0,...,2.0,NaN,1.0,0.0,NaN,2.0,NaN,0.0,2.0,2.0
E353-B3_3_7_6802_478,6802,0.0,0.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,...,1.0,2.0,1.0,NaN,NaN,NaN,0.0,0.0,2.0,NaN
E353-B3_3_14_6986_371,6986,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,...,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,NaN

In [12]:
print(len(df_samples))
print(df.shape)

1467
(1467, 43044)

In [11]:
df = df.drop(columns = ['POP'])
df.head()

,55749196-29-G/A,100283399-40-C/T,100283400-45-A/C,55750931-10-C/T,23141276-42-T/A,100283428-17-C/T,100283429-66-T/A,23147835-9-C/T,100283457-18-C/A,55764801-6-G/A,...,13501202-27-G/A,55836668-31-A/C,23157730-22-T/G,55846148-65-T/C,55860316-28-G/C,55836449-6-T/C,55863991-48-C/T,102640963-40-T/A,55816615-37-A/G,102641000-63-A/G
id,,,,,,,,,,,,,,,,,,,,,
E353-B1_3_6_333_001,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,0.0,0.0,0.0,NaN,0.0,0.0,2.0,NaN
E353-B1_3_6_6914_073,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,...,1.0,2.0,0.0,0.0,0.0,2.0,1.0,NaN,2.0,NaN
E353-B1_3_16_6917_081,0.0,0.0,2.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,...,2.0,NaN,1.0,0.0,NaN,2.0,NaN,0.0,2.0,2.0
E353-B3_3_7_6802_478,0.0,0.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.0,2.0,1.0,NaN,NaN,NaN,0.0,0.0,2.0,NaN
E353-B3_3_14_6986_371,0.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,NaN,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,NaN

# Metadata

Selecting samples from the TRAIN dataset

In [13]:
#dall = pd.read_csv("../44_train_and_test/00_combine_samples.tsv", sep="\t", header=0)
#gall = dall.groupby(["SET","Trait_name","SITE_ID"])["value"].count().reset_index()
##gall.to_excel('01_frequencies_stats.xlsx')
## number stats
#gall.set_index(["SET","Trait_name","SITE_ID"]).unstack().reset_index().to_excel('01_frequencies_stats.xlsx')

In [15]:
dmeta = pd.read_csv("../44_train_and_test/00_combine_samples.tsv", sep="\t", header=0)

# Subset only TRAIN
dmeta = dmeta[dmeta['SET'] == 'TRAIN'].reset_index(drop=True)
#dmeta = dmeta.set_index("genotype")
print(dmeta.shape)
dmeta.head()

(18282, 9)

,genotype,POP_ID,SITE_ID,call_rate,good_genotype,value,Trait_name,SET,POP_SITE
0,E60-A_4_1_62_260,332,AC,0.870518,True,559.411198,Average_Ring_Density,TRAIN,332_AC
1,E60-A_4_2_62_261,332,AC,0.852943,True,729.561198,Average_Ring_Density,TRAIN,332_AC
2,E60-A_4_7_62_264,332,AC,0.927686,True,565.111198,Average_Ring_Density,TRAIN,332_AC
3,E60-A_5_4_62_562,332,AC,0.898479,True,623.921198,Average_Ring_Density,TRAIN,332_AC
4,E60-A_5_5_62_563,332,AC,0.886400,True,NaN,Average_Ring_Density,TRAIN,332_AC

In [16]:
# Check if there are any pop-sites with less than 5 samples

#dmeta.groupby(["POP_SITE","Trait_name"])[["POP_ID"]].count().hist()
stats = dmeta.groupby(["POP_SITE","Trait_name"])[["genotype"]].count().reset_index()
stats[stats["genotype"] <= 4]

Empty DataFrame
Columns: [POP_SITE, Trait_name, genotype]
Index: []

# Loop for each trait

In [17]:
traits = dmeta['Trait_name'].drop_duplicates().values.tolist()
traits

['Average_Ring_Density',
 'Biomass_Increment',
 'Biomass_Increment_1980',
 'Biomass_Increment_1985',
 'Biomass_Increment_1990',
 'Biomass_Increment_1995',
 'Biomass_Increment_2000',
 'Biomass_Increment_2005',
 'Biomass_Increment_2010',
 'Biomass_Increment_2015',
 'DBH',
 'Height',
 'Rc',
 'Rl',
 'Rr',
 'Rs']

In [18]:
# random 10000

In [20]:
np.random.seed(3092025)
df_rand = df.sample(n=100, axis=1)
print(df_rand.shape)
df_rand.head()

(1467, 100)

,55792537-8-T/G,23142948-63-C/G,55834045-37-C/T,55845126-58-C/T,55818023-65-G/A,101753144-16-C/A,55804271-27-C/A,55830016-44-G/A,101657214-26-T/G,55774888-40-T/C,...,55858899-25-G/A,101919862-28-T/A,55807748-32-T/C,13491780-64-T/A,55814113-31-T/A,13487470-6-A/G,55842649-48-C/T,23141069-38-G/C,13492906-38-C/G,55810512-37-A/T
id,,,,,,,,,,,,,,,,,,,,,
E353-B1_3_6_333_001,0.0,0.0,2.0,0.0,1.0,NaN,0.0,0.0,0.0,0.0,...,0.0,NaN,2.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0
E353-B1_3_6_6914_073,0.0,0.0,2.0,0.0,2.0,NaN,0.0,1.0,0.0,0.0,...,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
E353-B1_3_16_6917_081,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
E353-B3_3_7_6802_478,1.0,0.0,2.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,...,0.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
E353-B3_3_14_6986_371,1.0,0.0,1.0,0.0,1.0,NaN,0.0,NaN,0.0,0.0,...,0.0,2.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0

In [22]:
for trait in traits:

    print(trait)
    # Data subset
    dmeta_sub = dmeta[dmeta['Trait_name'] == trait].reset_index(drop=True)
    dmeta_sub = dmeta_sub.set_index("genotype")
    
    # Subset genotypes present in metadata (TRAIN)
    df_sub = df_rand.loc[dmeta_sub.index.values]
    print(df_sub.shape)

    # Calculating frequencies
    df_all = df_sub.groupby(dmeta_sub['POP_SITE']).count()*2
    
    df_alleles = df_sub.groupby(dmeta_sub['POP_SITE']).sum()
    
    df_af = df_alleles.div(df_all)
    print(df_af.shape)
    stats_1 = df_af.shape[1]

    # Checking snps with no variation
    col_sums = df_af.sum()
    cols_to_exclude = col_sums[col_sums==0].index.values.tolist()
    df_af = df_af.drop(columns = cols_to_exclude)
    print(df_af.shape)
    stats_2 = df_af.shape[1]

    # Checking snps with nans
    nan_cols = df_af.columns[df_af.isna().any()].tolist()
    df_af = df_af.drop(columns = nan_cols)
    stats_3 = df_af.shape
    print(trait, stats_1, stats_2, stats_3)
    

    # Saving
    df_af.to_csv('01_frequencies_POP_100_' + trait + '.tsv', sep='\t', index=True, header=True)

Average_Ring_Density
(1266, 100)
(115, 100)
(115, 99)
Average_Ring_Density 100 99 (115, 97)
Biomass_Increment
(1266, 100)
(115, 100)
(115, 99)
Biomass_Increment 100 99 (115, 97)
Biomass_Increment_1980
(683, 100)
(87, 100)
(87, 94)
Biomass_Increment_1980 100 94 (87, 90)
Biomass_Increment_1985
(1114, 100)
(110, 100)
(110, 95)
Biomass_Increment_1985 100 95 (110, 92)
Biomass_Increment_1990
(1250, 100)
(114, 100)
(114, 99)
Biomass_Increment_1990 100 99 (114, 97)
Biomass_Increment_1995
(1266, 100)
(115, 100)
(115, 99)
Biomass_Increment_1995 100 99 (115, 97)
Biomass_Increment_2000
(1266, 100)
(115, 100)
(115, 99)
Biomass_Increment_2000 100 99 (115, 97)
Biomass_Increment_2005
(1259, 100)
(114, 100)
(114, 99)
Biomass_Increment_2005 100 99 (114, 97)
Biomass_Increment_2010
(1238, 100)
(113, 100)
(113, 99)
Biomass_Increment_2010 100 99 (113, 97)
Biomass_Increment_2015
(694, 100)
(83, 100)
(83, 92)
Biomass_Increment_2015 100 92 (83, 89)
DBH
(1257, 100)
(115, 100)
(115, 99)
DBH 100 99 (115, 97)
Height
(1257, 100)
(115, 100)
(115, 99)
Height 100 99 (115, 97)
Rc
(1267, 100)
(115, 100)
(115, 99)
Rc 100 99 (115, 97)
Rl
(1267, 100)
(115, 100)
(115, 99)
Rl 100 99 (115, 97)
Rr
(665, 100)
(82, 100)
(82, 94)
Rr 100 94 (82, 90)
Rs
(1267, 100)
(115, 100)
(115, 99)
Rs 100 99 (115, 97)

# random 1000

In [23]:
np.random.seed(3092025)
df_rand = df.sample(n=1000, axis=1)
print(df_rand.shape)
df_rand.head()

(1467, 1000)

,55792537-8-T/G,23142948-63-C/G,55834045-37-C/T,55845126-58-C/T,55818023-65-G/A,101753144-16-C/A,55804271-27-C/A,55830016-44-G/A,101657214-26-T/G,55774888-40-T/C,...,55795003-66-A/T,101152378-11-C/A,102431242-17-C/T,55791370-8-C/A,13512712-27-C/T,13497026-28-C/A,55806925-38-T/G,102510504-65-G/A,13503017-7-C/A,13493048-50-C/G
id,,,,,,,,,,,,,,,,,,,,,
E353-B1_3_6_333_001,0.0,0.0,2.0,0.0,1.0,NaN,0.0,0.0,0.0,0.0,...,0.0,2.0,2.0,0.0,0.0,0.0,0.0,NaN,0,0.0
E353-B1_3_6_6914_073,0.0,0.0,2.0,0.0,2.0,NaN,0.0,1.0,0.0,0.0,...,0.0,2.0,2.0,0.0,1.0,0.0,0.0,NaN,0,0.0
E353-B1_3_16_6917_081,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,2.0,2.0,NaN,0.0,0.0,0.0,2.0,0,0.0
E353-B3_3_7_6802_478,1.0,0.0,2.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,...,0.0,2.0,2.0,0.0,0.0,0.0,0.0,2.0,0,0.0
E353-B3_3_14_6986_371,1.0,0.0,1.0,0.0,1.0,NaN,0.0,NaN,0.0,0.0,...,0.0,2.0,2.0,NaN,0.0,0.0,0.0,NaN,0,0.0

In [24]:
for trait in traits:

    print(trait)
    # Data subset
    dmeta_sub = dmeta[dmeta['Trait_name'] == trait].reset_index(drop=True)
    dmeta_sub = dmeta_sub.set_index("genotype")
    
    # Subset genotypes present in metadata (TRAIN)
    df_sub = df_rand.loc[dmeta_sub.index.values]
    print(df_sub.shape)

    # Calculating frequencies
    df_all = df_sub.groupby(dmeta_sub['POP_SITE']).count()*2
    
    df_alleles = df_sub.groupby(dmeta_sub['POP_SITE']).sum()
    
    df_af = df_alleles.div(df_all)
    print(df_af.shape)
    stats_1 = df_af.shape[1]

    # Checking snps with no variation
    col_sums = df_af.sum()
    cols_to_exclude = col_sums[col_sums==0].index.values.tolist()
    df_af = df_af.drop(columns = cols_to_exclude)
    print(df_af.shape)
    stats_2 = df_af.shape[1]

    # Checking snps with nans
    nan_cols = df_af.columns[df_af.isna().any()].tolist()
    df_af = df_af.drop(columns = nan_cols)
    stats_3 = df_af.shape
    print(trait, stats_1, stats_2, stats_3)
    

    # Saving
    df_af.to_csv('01_frequencies_POP_1000_' + trait + '.tsv', sep='\t', index=True, header=True)

Average_Ring_Density
(1266, 1000)
(115, 1000)
(115, 987)
Average_Ring_Density 1000 987 (115, 969)
Biomass_Increment
(1266, 1000)
(115, 1000)
(115, 987)
Biomass_Increment 1000 987 (115, 969)
Biomass_Increment_1980
(683, 1000)
(87, 1000)
(87, 940)
Biomass_Increment_1980 1000 940 (87, 902)
Biomass_Increment_1985
(1114, 1000)
(110, 1000)
(110, 973)
Biomass_Increment_1985 1000 973 (110, 945)
Biomass_Increment_1990
(1250, 1000)
(114, 1000)
(114, 986)
Biomass_Increment_1990 1000 986 (114, 966)
Biomass_Increment_1995
(1266, 1000)
(115, 1000)
(115, 987)
Biomass_Increment_1995 1000 987 (115, 969)
Biomass_Increment_2000
(1266, 1000)
(115, 1000)
(115, 987)
Biomass_Increment_2000 1000 987 (115, 969)
Biomass_Increment_2005
(1259, 1000)
(114, 1000)
(114, 987)
Biomass_Increment_2005 1000 987 (114, 969)
Biomass_Increment_2010
(1238, 1000)
(113, 1000)
(113, 987)
Biomass_Increment_2010 1000 987 (113, 966)
Biomass_Increment_2015
(694, 1000)
(83, 1000)
(83, 939)
Biomass_Increment_2015 1000 939 (83, 906)
DBH
(1257, 1000)
(115, 1000)
(115, 984)
DBH 1000 984 (115, 966)
Height
(1257, 1000)
(115, 1000)
(115, 984)
Height 1000 984 (115, 966)
Rc
(1267, 1000)
(115, 1000)
(115, 987)
Rc 1000 987 (115, 969)
Rl
(1267, 1000)
(115, 1000)
(115, 987)
Rl 1000 987 (115, 969)
Rr
(665, 1000)
(82, 1000)
(82, 940)
Rr 1000 940 (82, 900)
Rs
(1267, 1000)
(115, 1000)
(115, 987)
Rs 1000 987 (115, 969)